FROM php:8.1-apache

ARG USERNAME=user
ARG GROUPNAME=user
ARG UID=1000
ARG GID=1000

RUN groupadd -g $GID $GROUPNAME && \
useradd -u $UID -g $GID $USERNAME && \
usermod -aG www-data $USERNAME

RUN apt-get update && apt-get install --assume-yes --no-install-recommends --quiet \
  unzip \
  vim \
  libicu-dev \
  && docker-php-ext-install \
  pdo_mysql \
  intl \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Composerをセットアップ
COPY --from=composer /usr/bin/composer /usr/bin/composer

# Node.jsをセットアップ
RUN curl -sL https://deb.nodesource.com/setup_16.x -o nodesource_setup.sh
RUN ["sh",  "./nodesource_setup.sh"]

WORKDIR /var/www/html
COPY ./apache2/sites-available/000-default.conf /etc/apache2/sites-available/000-default.conf
RUN a2enmod headers rewrite expires
RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini

USER $USERNAME

EXPOSE 80