version: "3"

services:
  php:
    build:
      dockerfile: Dockerfile.dev
    platform: linux/x86_64
    container_name: php
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
  mysql:
    platform: linux/x86_64
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_app
      MYSQL_USER: my_app
      MYSQL_PASSWORD: secret
      TZ: "Asia/Tokyo"
    volumes:
      - pg-data:/var/lib/mysql
    ports:
      - 3306:3306
      
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mysql
    - PMA_USER=root
    - PMA_PASSWORD=root
    ports:
      - 8080:80
    volumes:
      - ./prod/phpmyadmin-misc.ini:/usr/local/etc/php/conf.d/phpmyadmin-misc.ini

volumes:
  db-data:
  pg-data:

